/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

/**
 *
 * @author DevTech
 */
public class ProjectDilogScreen extends javax.swing.JDialog {

    /**
     * Creates new form ProjectDilogScreen
     */
    public ProjectDilogScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelToolbarProjects = new javax.swing.JPanel();
        jLabelToolbarTextProject = new javax.swing.JLabel();
        jLabelToolbarIconProject = new javax.swing.JLabel();
        jPanelCadastroProjeto = new javax.swing.JPanel();
        jLabelCadastroProjetoText = new javax.swing.JLabel();
        jTextFieldCadastroProjetoName = new javax.swing.JTextField();
        jLabelCadastroProjetoTextDescription = new javax.swing.JLabel();
        jScrollPaneDescriptionProject = new javax.swing.JScrollPane();
        jTextAreaDescriptionProject = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelToolbarProjects.setBackground(new java.awt.Color(0, 102, 102));

        jLabelToolbarTextProject.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelToolbarTextProject.setForeground(new java.awt.Color(255, 255, 255));
        jLabelToolbarTextProject.setText("Projetos");

        jLabelToolbarIconProject.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelToolbarIconProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/verifica.png"))); // NOI18N

        javax.swing.GroupLayout jPanelToolbarProjectsLayout = new javax.swing.GroupLayout(jPanelToolbarProjects);
        jPanelToolbarProjects.setLayout(jPanelToolbarProjectsLayout);
        jPanelToolbarProjectsLayout.setHorizontalGroup(
            jPanelToolbarProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolbarProjectsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelToolbarTextProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelToolbarIconProject, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelToolbarProjectsLayout.setVerticalGroup(
            jPanelToolbarProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelToolbarProjectsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelToolbarProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelToolbarTextProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelToolbarIconProject, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelCadastroProjeto.setBackground(new java.awt.Color(255, 255, 255));

        jLabelCadastroProjetoText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCadastroProjetoText.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCadastroProjetoText.setText("Nome");

        jTextFieldCadastroProjetoName.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCadastroProjetoName.setForeground(new java.awt.Color(0, 0, 0));

        jLabelCadastroProjetoTextDescription.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCadastroProjetoTextDescription.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCadastroProjetoTextDescription.setText("Descrição");

        jScrollPaneDescriptionProject.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPaneDescriptionProject.setForeground(new java.awt.Color(0, 0, 0));

        jTextAreaDescriptionProject.setBackground(new java.awt.Color(255, 255, 255));
        jTextAreaDescriptionProject.setColumns(20);
        jTextAreaDescriptionProject.setRows(5);
        jScrollPaneDescriptionProject.setViewportView(jTextAreaDescriptionProject);

        javax.swing.GroupLayout jPanelCadastroProjetoLayout = new javax.swing.GroupLayout(jPanelCadastroProjeto);
        jPanelCadastroProjeto.setLayout(jPanelCadastroProjetoLayout);
        jPanelCadastroProjetoLayout.setHorizontalGroup(
            jPanelCadastroProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroProjetoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPaneDescriptionProject, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                    .addComponent(jLabelCadastroProjetoText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldCadastroProjetoName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCadastroProjetoTextDescription, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelCadastroProjetoLayout.setVerticalGroup(
            jPanelCadastroProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroProjetoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCadastroProjetoText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldCadastroProjetoName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelCadastroProjetoTextDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneDescriptionProject, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelToolbarProjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCadastroProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelToolbarProjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCadastroProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectDilogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectDilogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectDilogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectDilogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProjectDilogScreen dialog = new ProjectDilogScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelCadastroProjetoText;
    private javax.swing.JLabel jLabelCadastroProjetoTextDescription;
    private javax.swing.JLabel jLabelToolbarIconProject;
    private javax.swing.JLabel jLabelToolbarTextProject;
    private javax.swing.JPanel jPanelCadastroProjeto;
    private javax.swing.JPanel jPanelToolbarProjects;
    private javax.swing.JScrollPane jScrollPaneDescriptionProject;
    private javax.swing.JTextArea jTextAreaDescriptionProject;
    private javax.swing.JTextField jTextFieldCadastroProjetoName;
    // End of variables declaration//GEN-END:variables
}
